# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Graphical_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(560, 678)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\resources/LOGO-128p.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(37, 37, 38);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Status_Label = QtWidgets.QLabel(self.centralwidget)
        self.Status_Label.setGeometry(QtCore.QRect(10, 79, 165, 24))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Status_Label.setFont(font)
        self.Status_Label.setStyleSheet("color: #ffffff;\n"
"")
        self.Status_Label.setObjectName("Status_Label")
        self.Progress_Bar = QtWidgets.QProgressBar(self.centralwidget)
        self.Progress_Bar.setGeometry(QtCore.QRect(190, 84, 360, 14))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(9)
        self.Progress_Bar.setFont(font)
        self.Progress_Bar.setStyleSheet("color: #ffffff;\n"
"")
        self.Progress_Bar.setProperty("value", 0)
        self.Progress_Bar.setObjectName("Progress_Bar")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 654, 701, 2))
        self.line.setStyleSheet("background-color: rgb(51, 51, 55);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Version_Title_Label = QtWidgets.QLabel(self.centralwidget)
        self.Version_Title_Label.setGeometry(QtCore.QRect(10, 632, 70, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.Version_Title_Label.setFont(font)
        self.Version_Title_Label.setStyleSheet("color: #ffffff;\n"
"")
        self.Version_Title_Label.setObjectName("Version_Title_Label")
        self.Version_Display_Label = QtWidgets.QLabel(self.centralwidget)
        self.Version_Display_Label.setGeometry(QtCore.QRect(82, 632, 100, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.Version_Display_Label.setFont(font)
        self.Version_Display_Label.setStyleSheet("color: #ffffff;\n"
"")
        self.Version_Display_Label.setText("")
        self.Version_Display_Label.setObjectName("Version_Display_Label")
        self.dayTime_Display = QtWidgets.QLineEdit(self.centralwidget)
        self.dayTime_Display.setGeometry(QtCore.QRect(356, 5, 194, 24))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dayTime_Display.setFont(font)
        self.dayTime_Display.setMouseTracking(False)
        self.dayTime_Display.setAutoFillBackground(False)
        self.dayTime_Display.setStyleSheet("background-color: #000000;\n"
"color: #00ff00;\n"
"")
        self.dayTime_Display.setText("")
        self.dayTime_Display.setAlignment(QtCore.Qt.AlignCenter)
        self.dayTime_Display.setReadOnly(True)
        self.dayTime_Display.setObjectName("dayTime_Display")
        self.Title_Label = QtWidgets.QLabel(self.centralwidget)
        self.Title_Label.setGeometry(QtCore.QRect(10, 34, 285, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Title_Label.setFont(font)
        self.Title_Label.setStyleSheet("color: #8bc34a;\n"
"")
        self.Title_Label.setObjectName("Title_Label")
        self.Select_File_Label = QtWidgets.QLabel(self.centralwidget)
        self.Select_File_Label.setGeometry(QtCore.QRect(10, 143, 180, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Select_File_Label.setFont(font)
        self.Select_File_Label.setStyleSheet("color: #ffffff;\n"
"")
        self.Select_File_Label.setObjectName("Select_File_Label")
        self.File_Path_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.File_Path_Edit.setGeometry(QtCore.QRect(10, 167, 426, 24))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setKerning(True)
        self.File_Path_Edit.setFont(font)
        self.File_Path_Edit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.File_Path_Edit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.File_Path_Edit.setStyleSheet("QLineEdit{\n"
"background-color: #333337;\n"
"border: 1px solid #7a7a7a;\n"
"color: #ffffff;\n"
"}\n"
"QLineEdit:hover{\n"
"background-color: #1f1f1f;\n"
"border: 1px solid #7a7a7a;\n"
"color: #ffffff;\n"
"}\n"
"")
        self.File_Path_Edit.setText("")
        self.File_Path_Edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.File_Path_Edit.setClearButtonEnabled(True)
        self.File_Path_Edit.setObjectName("File_Path_Edit")
        self.Select_File_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Select_File_Button.setGeometry(QtCore.QRect(450, 165, 100, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Select_File_Button.setFont(font)
        self.Select_File_Button.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Select_File_Button.setStyleSheet("QPushButton{\n"
"background-color: rgb(49, 54, 59);\n"
"border: 2px;\n"
"border-color: rgb(139, 195, 74);\n"
"border-style: solid;\n"
"border-radius: 0px;\n"
"color: rgb(139, 195, 74);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(139, 195, 74);\n"
"color: rgb(49, 54, 59);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius: 0px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(79, 91, 98);\n"
"border: 2px;\n"
"border-color: rgb(49, 54, 59);\n"
"border-style: solid;\n"
"border-radius: 0px;\n"
"color: rgb(49, 54, 59);\n"
"}")
        self.Select_File_Button.setObjectName("Select_File_Button")
        self.Scripts_Label = QtWidgets.QLabel(self.centralwidget)
        self.Scripts_Label.setGeometry(QtCore.QRect(10, 233, 380, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Scripts_Label.setFont(font)
        self.Scripts_Label.setStyleSheet("color: #ffffff;\n"
"")
        self.Scripts_Label.setObjectName("Scripts_Label")
        self.Scripts_Edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Scripts_Edit.setGeometry(QtCore.QRect(10, 257, 540, 140))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Scripts_Edit.setFont(font)
        self.Scripts_Edit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Scripts_Edit.setStyleSheet("QPlainTextEdit{\n"
"background-color: #333337;\n"
"border: 1px solid #7a7a7a;\n"
"color: #ffffff;\n"
"}\n"
"QPlainTextEdit:hover{\n"
"background-color: #1f1f1f;\n"
"border: 1px solid #7a7a7a;\n"
"color: #ffffff;\n"
"}\n"
"")
        self.Scripts_Edit.setPlainText("")
        self.Scripts_Edit.setObjectName("Scripts_Edit")
        self.Start_Main_Task_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Main_Task_Button.setEnabled(True)
        self.Start_Main_Task_Button.setGeometry(QtCore.QRect(150, 407, 260, 38))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Start_Main_Task_Button.setFont(font)
        self.Start_Main_Task_Button.setStyleSheet("QPushButton{\n"
"background-color: rgb(49, 54, 59);\n"
"border: 2px;\n"
"border-color: rgb(139, 195, 74);\n"
"border-style: solid;\n"
"border-radius: 5px;\n"
"color: rgb(139, 195, 74);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(139, 195, 74);\n"
"color: rgb(49, 54, 59);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(79, 91, 98);\n"
"border: 2px;\n"
"border-color: rgb(49, 54, 59);\n"
"border-style: solid;\n"
"border-radius: 5px;\n"
"color: rgb(49, 54, 59);\n"
"}")
        self.Start_Main_Task_Button.setObjectName("Start_Main_Task_Button")
        self.Message_Display_Label = QtWidgets.QLabel(self.centralwidget)
        self.Message_Display_Label.setGeometry(QtCore.QRect(10, 455, 130, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Message_Display_Label.setFont(font)
        self.Message_Display_Label.setStyleSheet("color: #ffffff;\n"
"")
        self.Message_Display_Label.setObjectName("Message_Display_Label")
        self.Message_Display_Edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.Message_Display_Edit.setGeometry(QtCore.QRect(10, 477, 380, 140))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Message_Display_Edit.setFont(font)
        self.Message_Display_Edit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Message_Display_Edit.setStyleSheet("background-color: #333337;\n"
"border: 1px solid #7a7a7a;\n"
"color: #ffffff;\n"
"")
        self.Message_Display_Edit.setReadOnly(True)
        self.Message_Display_Edit.setPlainText("")
        self.Message_Display_Edit.setObjectName("Message_Display_Edit")
        self.Open_Saved_Dir_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Open_Saved_Dir_Button.setGeometry(QtCore.QRect(410, 589, 140, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Open_Saved_Dir_Button.setFont(font)
        self.Open_Saved_Dir_Button.setStyleSheet("QPushButton{\n"
"background-color: rgb(49, 54, 59);\n"
"border: 2px;\n"
"border-color: rgb(139, 195, 74);\n"
"border-style: solid;\n"
"border-radius: 0px;\n"
"color: rgb(139, 195, 74);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(139, 195, 74);\n"
"color: rgb(49, 54, 59);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius: 0px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(79, 91, 98);\n"
"border: 2px;\n"
"border-color: rgb(49, 54, 59);\n"
"border-style: solid;\n"
"border-radius: 0px;\n"
"color: rgb(49, 54, 59);\n"
"}")
        self.Open_Saved_Dir_Button.setObjectName("Open_Saved_Dir_Button")
        self.Connect_By_Telnet_Button = QtWidgets.QRadioButton(self.centralwidget)
        self.Connect_By_Telnet_Button.setEnabled(True)
        self.Connect_By_Telnet_Button.setGeometry(QtCore.QRect(294, 201, 142, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Connect_By_Telnet_Button.setFont(font)
        self.Connect_By_Telnet_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Connect_By_Telnet_Button.setAutoFillBackground(False)
        self.Connect_By_Telnet_Button.setStyleSheet("color: rgb(255, 255, 127);\n"
"")
        self.Connect_By_Telnet_Button.setChecked(False)
        self.Connect_By_Telnet_Button.setAutoRepeat(True)
        self.Connect_By_Telnet_Button.setObjectName("Connect_By_Telnet_Button")
        self.Connect_By_SSH_Button = QtWidgets.QRadioButton(self.centralwidget)
        self.Connect_By_SSH_Button.setEnabled(True)
        self.Connect_By_SSH_Button.setGeometry(QtCore.QRect(152, 201, 142, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Connect_By_SSH_Button.setFont(font)
        self.Connect_By_SSH_Button.setStyleSheet("color: rgb(255, 255, 127);\n"
"")
        self.Connect_By_SSH_Button.setChecked(True)
        self.Connect_By_SSH_Button.setObjectName("Connect_By_SSH_Button")
        self.Select_Protocol_Label = QtWidgets.QLabel(self.centralwidget)
        self.Select_Protocol_Label.setGeometry(QtCore.QRect(10, 201, 142, 22))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Select_Protocol_Label.setFont(font)
        self.Select_Protocol_Label.setStyleSheet("color: #ffffff;\n"
"")
        self.Select_Protocol_Label.setObjectName("Select_Protocol_Label")
        self.Message_Display_Clear_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Message_Display_Clear_Button.setEnabled(True)
        self.Message_Display_Clear_Button.setGeometry(QtCore.QRect(410, 551, 140, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Message_Display_Clear_Button.setFont(font)
        self.Message_Display_Clear_Button.setStyleSheet("QPushButton{\n"
"background-color: rgb(49, 54, 59);\n"
"border: 2px;\n"
"border-color: rgb(255, 0, 0);\n"
"border-style: solid;\n"
"border-radius: 0px;\n"
"color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px;\n"
"border-color: rgb(255, 0, 0);\n"
"border-style: solid;\n"
"border-radius: 0px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(79, 91, 98);\n"
"border: 2px;\n"
"border-color: rgb(49, 54, 59);\n"
"border-style: solid;\n"
"border-radius: 0px;\n"
"color: rgb(49, 54, 59);\n"
"}")
        self.Message_Display_Clear_Button.setCheckable(False)
        self.Message_Display_Clear_Button.setChecked(False)
        self.Message_Display_Clear_Button.setObjectName("Message_Display_Clear_Button")
        self.Start_Main_Task_Button_Fake = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Main_Task_Button_Fake.setEnabled(False)
        self.Start_Main_Task_Button_Fake.setGeometry(QtCore.QRect(150, 407, 260, 38))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Start_Main_Task_Button_Fake.setFont(font)
        self.Start_Main_Task_Button_Fake.setStyleSheet("QPushButton{\n"
"background-color: rgb(49, 54, 59);\n"
"border: 2px;\n"
"border-color: rgb(139, 195, 74);\n"
"border-style: solid;\n"
"border-radius: 5px;\n"
"color: rgb(139, 195, 74);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(139, 195, 74);\n"
"color: rgb(49, 54, 59);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px;\n"
"border-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(79, 91, 98);\n"
"border: 2px;\n"
"border-color: rgb(49, 54, 59);\n"
"border-style: solid;\n"
"border-radius: 5px;\n"
"color: rgb(49, 54, 59);\n"
"}")
        self.Start_Main_Task_Button_Fake.setObjectName("Start_Main_Task_Button_Fake")
        self.Message_Display_Clear_Button_Fake = QtWidgets.QPushButton(self.centralwidget)
        self.Message_Display_Clear_Button_Fake.setEnabled(False)
        self.Message_Display_Clear_Button_Fake.setGeometry(QtCore.QRect(410, 551, 140, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Message_Display_Clear_Button_Fake.setFont(font)
        self.Message_Display_Clear_Button_Fake.setStyleSheet("QPushButton{\n"
"background-color: rgb(49, 54, 59);\n"
"border: 2px;\n"
"border-color: rgb(255, 0, 0);\n"
"border-style: solid;\n"
"border-radius: 0px;\n"
"color: rgb(255, 255, 127);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px;\n"
"border-color: rgb(255, 0, 0);\n"
"border-style: solid;\n"
"border-radius: 0px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:disabled{\n"
"background-color: rgb(79, 91, 98);\n"
"border: 2px;\n"
"border-color: rgb(49, 54, 59);\n"
"border-style: solid;\n"
"border-radius: 0px;\n"
"color: rgb(49, 54, 59);\n"
"}")
        self.Message_Display_Clear_Button_Fake.setCheckable(False)
        self.Message_Display_Clear_Button_Fake.setChecked(False)
        self.Message_Display_Clear_Button_Fake.setObjectName("Message_Display_Clear_Button_Fake")
        self.Copyright_Display_Label = QtWidgets.QLabel(self.centralwidget)
        self.Copyright_Display_Label.setGeometry(QtCore.QRect(365, 632, 185, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.Copyright_Display_Label.setFont(font)
        self.Copyright_Display_Label.setStyleSheet("color: #ffffff;\n"
"")
        self.Copyright_Display_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Copyright_Display_Label.setObjectName("Copyright_Display_Label")
        self.Count_Status_Label = QtWidgets.QLabel(self.centralwidget)
        self.Count_Status_Label.setGeometry(QtCore.QRect(49, 113, 350, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Count_Status_Label.setFont(font)
        self.Count_Status_Label.setStyleSheet("color: #8bc34a;\n"
"")
        self.Count_Status_Label.setText("")
        self.Count_Status_Label.setObjectName("Count_Status_Label")
        self.Message_Display_Clear_Button_Fake.raise_()
        self.Start_Main_Task_Button_Fake.raise_()
        self.Status_Label.raise_()
        self.Progress_Bar.raise_()
        self.line.raise_()
        self.Version_Title_Label.raise_()
        self.Version_Display_Label.raise_()
        self.dayTime_Display.raise_()
        self.Title_Label.raise_()
        self.Select_File_Label.raise_()
        self.File_Path_Edit.raise_()
        self.Select_File_Button.raise_()
        self.Scripts_Label.raise_()
        self.Scripts_Edit.raise_()
        self.Start_Main_Task_Button.raise_()
        self.Message_Display_Label.raise_()
        self.Message_Display_Edit.raise_()
        self.Open_Saved_Dir_Button.raise_()
        self.Connect_By_Telnet_Button.raise_()
        self.Connect_By_SSH_Button.raise_()
        self.Select_Protocol_Label.raise_()
        self.Message_Display_Clear_Button.raise_()
        self.Copyright_Display_Label.raise_()
        self.Count_Status_Label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Inspect Helper GUI"))
        self.Status_Label.setText(_translate("MainWindow", "状态：等待执行"))
        self.Version_Title_Label.setText(_translate("MainWindow", "程序版本："))
        self.Title_Label.setText(_translate("MainWindow", "网络设备批量运维助手"))
        self.Select_File_Label.setText(_translate("MainWindow", "选择设备信息文件："))
        self.Select_File_Button.setText(_translate("MainWindow", "选择文件"))
        self.Scripts_Label.setText(_translate("MainWindow", "输入需要按顺序执行的命令（一行一个）："))
        self.Start_Main_Task_Button.setText(_translate("MainWindow", "开始执行"))
        self.Message_Display_Label.setText(_translate("MainWindow", "运行状态信息："))
        self.Open_Saved_Dir_Button.setText(_translate("MainWindow", "浏览保存目录"))
        self.Connect_By_Telnet_Button.setText(_translate("MainWindow", "使用Telnet连接"))
        self.Connect_By_SSH_Button.setText(_translate("MainWindow", "使用SSH连接"))
        self.Select_Protocol_Label.setText(_translate("MainWindow", "选择连接方式："))
        self.Message_Display_Clear_Button.setText(_translate("MainWindow", "清空状态信息"))
        self.Start_Main_Task_Button_Fake.setText(_translate("MainWindow", "开始执行"))
        self.Message_Display_Clear_Button_Fake.setText(_translate("MainWindow", "清空状态信息"))
        self.Copyright_Display_Label.setText(_translate("MainWindow", "© 2022-2023 Vincent慕远"))
